### ISSUE TITLE
converter: Incorrect highlight column when multibyte characters are in items

### ISSUE THREAD

**Issue by Milly** [tani/ddc-fuzzy#6]
`PumHighlight.col` is bytes position in vim, not character count.

![image](https://user-images.githubusercontent.com/22977/202223511-abffb043-3474-4b10-8498-e09551e2fae3.png)

I wrote the test below.
https://github.com/Milly/ddc-fuzzy/commit/0420d43f3208d53c4c44faa54100d2cb4fbaf2f3

**Comment by Milly** [comment]
This test won't work out of the box, even with an implementation, as it requires a call to vim's `strlen`.

**Comment by tani** [comment]
I see that the problem is:

- In JS, the column position is calculated as is.
- In Vim, Pum refers the raw column position calculated in JS but
  it is expected to declare the byte-width position.

Then, the only way is to calculate the byte-width position in JS.
I have no time to implement this method in this month.
I can review but I will not able to  write any code aggressively.

I am sponsored by someone using GitHub sponsors campaign for this project.
Thus, I promise to fix this issue in near future but it is not now.
Please understand my situation. Best regards,

**Comment by tani** [comment]
Of course, the pull request is always welcome. It would be nice for us :)

**Comment by Milly** [comment]
I have already made a fix.
Can we use `denops.eval` there?
This is for better performance.

**Comment by tani** [comment]
Wow. it's awesome.

> Can we use denops.eval there?

Honestly, I am not sure for the performance.
However, it is time to try it. Please do that as you want.
If we face some problems, then let us revert it.
